function noisy_3d_data = addPMTShotNoise3D(original_3d_data, darkCurrentPhotons, conversionFactor)
%ADDPMTSHOTNOISE3D Adds PMT shot noise and dark current noise to 3D data.
%   noisy_3d_data = addPMTShotNoise3D(original_3d_data, darkCurrentPhotons, conversionFactor)
%
%   Args:
%       original_3d_data (double/single): Ground-truth 3D data.
%                                         Pixel values are assumed to be proportional to the mean
%                                         signal photon counts. Larger values correspond to stronger signals.
%       darkCurrentPhotons (double):  Mean number of photons generated by dark current per voxel.
%                                    This noise component is particularly important under low-signal or dark-field conditions.
%       conversionFactor (double, optional):
%           Conversion factor from image intensity to mean photon counts.
%           If original_3d_data already represents mean photon counts,
%           set conversionFactor = 1.
%
%           Example:
%           If an intensity value of 255 corresponds to 1000 photons,
%           then conversionFactor = 1000/255.
%
%           Default: 1.
%
%   Output:
%       noisy_3d_data (double):
%           3D data corrupted by shot noise and dark current noise.

    % Ensure double precision for numerical calculations
    original_3d_data = double(original_3d_data);

    % Handle optional conversion factor
    if nargin < 3 || isempty(conversionFactor)
        conversionFactor = 1.0; % Default = 1, assuming original_3d_data is already expressed in mean photon counts.
    end

    % 1. Calculate the mean signal photon count per voxel.
    %    The original intensity values are converted into expected
    %    photon counts using the conversion factor.
    mean_signal_photons = original_3d_data * conversionFactor;
    
    % Ensure non-negative photon counts
    mean_signal_photons(mean_signal_photons < 0) = 0;

    % 2. Calculate the total expected photon count, including
    %    both signal photons and dark current photons.
    %
    %    Dark current originates from stochastic processes such as
    %    thermally generated electrons and therefore also follows
    %    Poisson statistics.
    %
    %    Consequently, dark current can be incorporated by directly
    %    adding its mean photon count to the signal expectation.
    mean_total_photons = mean_signal_photons + darkCurrentPhotons;

    %    Safety check
    mean_total_photons(mean_total_photons < 0) = 0;

    % 3. Generate Poisson-distributed photon counts.
    %
    %    This step simultaneously models:
    %    (i) signal-dependent shot noise
    %    (ii) dark current noise
    noisy_photons = poissrnd(mean_total_photons);

    % 4. Convert photon counts back to the original intensity scale.
    %
    %    This allows direct comparison with the input data.
    noisy_3d_data = noisy_photons / conversionFactor; 
    
    % Optional: enforce non-negative intensities
    noisy_3d_data(noisy_3d_data < 0) = 0; 

end